name: unite
description: A new Flutter package,waiting for perfection.
version: 0.0.1
homepage: https://github.com/wraptor
repository: https://github.com/wraptor/unite

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_easyloading: ^3.0.0
  shared_preferences: ^2.0.6
  #dio网络请求 https://github.com/flutterchina/dio/blob/master/README-ZH.md
  dio: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: